### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by Paspartout** [UntitledAuthors/UntitledCreatureMod#8]
These are some things that have to be done before relasing the mod to the public. Noted here so we don't forget.

- [ ] Testing
  - [ ] Multiplayer
  - [ ] Blopole Flowerpot with modded flowers
- [ ] Remove/Hide Debug Item
- [ ] Update README.md
  - [ ] Add lead/heading image for curseforge like [these](https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/1.15.X/README.md)
